#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l pmem=16gb
#PBS -l walltime=30:00:00
#PBS -A bfp2_k_g_bc_default
#PBS -o logs/starrpeaker.log.out
#PBS -e logs/starrpeaker.log.err
#PBS -t 1-3

module load gcc/9.3.1
module load anaconda3
source activate starrpeaker

WRK=/path/to/JamilsSTARRdata
WRK=/storage/home/owl5022/scratch/JamilsSTARRdata
cd $WRK

DBAM=results/BAM
DFILTER=results/filtered_BAM
DOUT=results/OUTPUT

[ -d logs ] || mkdir logs
[ -d $DOUT ] || mkdir $DOUT

METADATA=bam-samples.txt
INFO=`sed "${PBS_ARRAYID}q;d" $METADATA`
STARR=`echo $INFO | awk '{print $2}'`
INPUT=`echo $INFO | awk '{print $5}'`
#echo $INFO

BLACKLIST=input/ENCFF419RSJ.bed
COVGC=input/gc5Base.bw
GENOME=input/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz.pac
CHROMSIZES=input/hg38.chrom.sizes
CHROMSIZES=input/GRCh38.chrom.sizes.simple.sorted


start=`date +%s`
starrpeaker --prefix $DOUT/$STARR --chromsize $CHROMSIZES --blacklist $BLACKLIST \
	--input $DFILTER/$INPUT.bam --output $DFILTER/$STARR.bam --threshold 0.05
#	--cov <covariate 1: gc content> <covariate 2: mappability> <covariate 3: conservation> \
end=`date +%s`
runtime=$((end-start))
echo "Starrpeaker ${STARR}-${INPUT} ran in ${runtime}"


